'use client'

import { useState } from 'react'
import { Bell, ChevronRight } from 'lucide-react'
import SectionHeader from '@/components/primitives/SectionHeader'
import AnalyticsStrip from '@/components/primitives/AnalyticsStrip'
import DetailChart from '@/components/primitives/DetailChart'
import InsightRow from '@/components/primitives/InsightRow'

export default function AlertsView() {
  const [filter, setFilter] = useState('Todos')
  const alerts = [{title:'Reporte prudencial vence em 5 dias', source:'Obrigações · BNA', time:'Há 12 min', tone:'critical', status:'Não lido'}, {title:'Novo normativo UIF requer avaliação', source:'Monitor regulatório · UIF', time:'Há 46 min', tone:'warning', status:'Não lido'}, {title:'Controlo AML-042 com eficácia abaixo do limite', source:'Controlos · AML / CFT', time:'Há 2 h', tone:'info', status:'Em acompanhamento'}, {title:'Novo acesso atribuído a João Manuel', source:'Segurança · Utilizadores', time:'Há 4 h', tone:'success', status:'Resolvido'}]
  const visible = filter === 'Todos' ? alerts : alerts.filter((a) => a.status === filter)
  return <div className="view-enter"><SectionHeader eyebrow="GESTÃO DA PLATAFORMA" title="Alertas e notificações" subtitle="Centralize alertas operacionais, regulatórios e de segurança num único centro." action="Criar regra de alerta"/><div className="view-body"><AnalyticsStrip items={[{label:'Alertas activos',value:'27',delta:'+6 hoje',tone:'blue'},{label:'Críticos',value:'03',delta:'Requerem ação imediata',tone:'red'},{label:'Não lidos',value:'11',delta:'−4 desde ontem',tone:'amber'},{label:'Regras activas',value:'18',delta:'+2 este mês',tone:'green'}]}/><div className="dashboard-grid grid-2col"><DetailChart title="Volume de alertas" subtitle="Detecções por dia · últimos 30 dias" tone="red"/><div className="card"><div className="card-header"><div><span className="card-eyebrow">ALERT GOVERNANCE</span><h3 className="card-title">Regras de monitorização</h3><p className="card-subtitle">Estado das regras activas</p></div></div><div className="card-content"><InsightRow label="Regulatório" value="8" detail="BNA, UIF e outros" tone="blue"/><InsightRow label="Operacional" value="6" detail="SLA e obrigações" tone="amber"/><InsightRow label="Segurança" value="4" detail="Acessos e permissões" tone="red"/></div></div></div><div className="card alert-inbox"><div className="card-header"><div><h3 className="card-title">Caixa de alertas</h3><p className="card-subtitle">Priorize e encaminhe as ocorrências da sua equipa</p></div><div className="alert-filters">{['Todos','Não lido','Em acompanhamento','Resolvido'].map((item) => <button key={item} className={filter === item ? 'active' : ''} onClick={() => setFilter(item)}>{item}</button>)}</div></div><div className="alert-list">{visible.map((alert) => <div className="alert-row" key={alert.title}><span className={`alert-symbol ${alert.tone}`}><Bell size={15}/></span><div className="alert-copy"><strong>{alert.title}</strong><small>{alert.source} · {alert.time}</small></div><span className={`status-pill ${alert.tone === 'critical' ? 'danger' : alert.tone === 'warning' ? 'warning' : 'success'}`}>{alert.status}</span><button className="btn btn-ghost">Abrir <ChevronRight size={14}/></button></div>)}</div></div></div></div>
}