'use client'

import { useState } from 'react'
import { ChevronRight } from 'lucide-react'
import SectionHeader from '@/components/primitives/SectionHeader'
import AnalyticsStrip from '@/components/primitives/AnalyticsStrip'
import CaseDrawer from '@/components/primitives/CaseDrawer'

export default function AllKycCasesView() {
  const [selectedCase, setSelectedCase] = useState<{ name:string; type:string; risk:string; status:string } | null>(null)
  const cases = [{name:'Empresa ABC Lda.',type:'KYC · Cliente',risk:'Baixo',status:'Completo'},{name:'Marta Domingos',type:'KYE · Colaborador',risk:'Médio',status:'Em revisão'},{name:'Fornecedor XYZ SA',type:'KYP · Parceiro',risk:'Alto',status:'Documentação pendente'},{name:'Grupo DEF SA',type:'KYC · Cliente',risk:'Baixo',status:'Completo'},{name:'Ana Costa',type:'KYE · Colaborador',risk:'Baixo',status:'Completo'}]
  return <div className="view-enter"><SectionHeader eyebrow="CLIENTE & KYC · KYE · KYP" title="Todos os casos de diligência" subtitle="Pesquise, filtre e abra o detalhe de qualquer caso de cliente, colaborador ou parceiro." action="Novo caso"/><div className="view-body"><AnalyticsStrip items={[{label:'Casos encontrados',value:'1.284',delta:'Todos os tipos',tone:'blue'},{label:'KYC · Clientes',value:'872',delta:'68% da carteira',tone:'green'},{label:'KYE · Colaboradores',value:'321',delta:'25% da carteira',tone:'purple'},{label:'KYP · Parceiros',value:'91',delta:'7% · 12 críticos',tone:'red'}]}/><div className="card cases-list-card"><div className="card-header"><div><span className="card-eyebrow">DUE DILIGENCE REGISTER</span><h3 className="card-title">Registo completo de casos</h3><p className="card-subtitle">Cada caso abre o detalhe operacional num painel lateral direito.</p></div><div className="cases-filter-row"><button className="btn btn-secondary">Filtrar tipo</button><button className="btn btn-secondary">Filtrar risco</button></div></div><div className="table-wrapper"><table className="table"><thead><tr><th>Nome / tipo</th><th>Segmento</th><th>Risco</th><th>Estado</th><th>Última atualização</th><th/></tr></thead><tbody>{cases.map((item,i)=><tr key={item.name}><td><button className="case-link" onClick={() => setSelectedCase(item)}><strong>{item.name}</strong><small>{item.type}</small></button></td><td>{['Corporate','Compliance','Fornecedor crítico','Institucional','Compliance'][i]}</td><td><span className={`risk-pill ${item.risk==='Alto'?'high':item.risk==='Médio'?'medium':'low'}`}>{item.risk}</span></td><td><span className={`status ${item.status==='Documentação pendente'?'warning':'success'}`}>{item.status}</span></td><td>Hoje, 09:{20+i}</td><td><button className="btn btn-ghost" onClick={() => setSelectedCase(item)}>Abrir <ChevronRight size={14}/></button></td></tr>)}</tbody></table></div></div>{selectedCase && <CaseDrawer item={selectedCase} onClose={() => setSelectedCase(null)}/>}</div></div>
}