'use client'

import { useState } from 'react'
import { CheckCircle2 } from 'lucide-react'

export default function AuthHub() {
  const [mode, setMode] = useState<'login' | 'forgot' | 'otp' | 'logout'>('login')
  const [submitted, setSubmitted] = useState(false)
  const titles = { login: 'Entrar na plataforma', forgot: 'Recuperar palavra-passe', otp: 'Verificação de segurança', logout: 'Sessão terminada' }
  if (submitted && mode !== 'logout') return <div className="auth-screen"><section className="auth-card"><div className="auth-mark">O</div><span className="section-kicker">OPAKUS SECURITY</span><h1>{mode === 'forgot' ? 'Link enviado' : 'Código validado'}</h1><p>{mode === 'forgot' ? 'Enviámos instruções para o seu email profissional.' : 'A sua identidade foi confirmada. Pode continuar para a workspace.'}</p><button className="btn btn-primary auth-full" onClick={() => { setSubmitted(false); setMode('login') }}>Voltar ao login</button></section></div>
  return <div className="auth-screen"><section className="auth-card"><div className="auth-mark">O</div><span className="section-kicker">OPAKUS · IDENTITY & ACCESS</span><h1>{titles[mode]}</h1><p className="auth-intro">Acesso seguro ao centro de conformidade.</p>{mode === 'logout' ? <><div className="logout-icon"><CheckCircle2 size={32}/></div><p>A sessão de Marta Domingos foi terminada com segurança.</p><button className="btn btn-primary auth-full" onClick={() => setMode('login')}>Entrar novamente</button></> : <form onSubmit={(event) => { event.preventDefault(); setSubmitted(true) }}>{mode === 'login' && <><label>Email profissional<input type="email" required placeholder="nome@organizacao.com"/></label><label>Palavra-passe<input type="password" required placeholder="••••••••••••"/></label><div className="auth-options"><label className="auth-check"><input type="checkbox"/> Manter sessão</label><button type="button" className="text-action" onClick={() => setMode('forgot')}>Esqueci a palavra-passe</button></div><button className="btn btn-primary auth-full">Entrar com segurança</button><button type="button" className="auth-secondary" onClick={() => setMode('otp')}>Usar código OTP</button></>}{mode === 'forgot' && <><label>Email profissional<input type="email" required placeholder="nome@organizacao.com"/></label><button className="btn btn-primary auth-full">Enviar instruções</button><button type="button" className="auth-secondary" onClick={() => setMode('login')}>Voltar ao login</button></>}{mode === 'otp' && <><p className="otp-hint">Introduza o código de 6 dígitos enviado para o seu dispositivo autenticador.</p><label>Código OTP<input inputMode="numeric" pattern="[0-9]{6}" minLength={6} maxLength={6} required placeholder="000000"/></label><button className="btn btn-primary auth-full">Validar código</button><button type="button" className="auth-secondary" onClick={() => setMode('login')}>Usar palavra-passe</button></>}</form>}<div className="auth-footer"><button onClick={() => setMode('logout')}>Terminar sessão</button><span>Protegido por Opakus IAM · MFA activo</span></div></section></div>
}