'use client'

import { useState } from 'react'
import { ChevronRight } from 'lucide-react'
import SectionHeader from '@/components/primitives/SectionHeader'
import AnalyticsStrip from '@/components/primitives/AnalyticsStrip'
import DetailChart from '@/components/primitives/DetailChart'
import InsightRow from '@/components/primitives/InsightRow'

export default function KycDetailView() {
  const [selectedCase, setSelectedCase] = useState<{ name: string; type: string; risk: string; status: string } | null>(null)
  const cases = [{ name:'Empresa ABC Lda.', type:'KYC · Cliente', risk:'Baixo', status:'Completo' }, { name:'Marta Domingos', type:'KYE · Colaborador', risk:'Médio', status:'Em revisão' }, { name:'Fornecedor XYZ SA', type:'KYP · Parceiro', risk:'Alto', status:'Documentação pendente' }, { name:'Grupo DEF SA', type:'KYC · Cliente', risk:'Baixo', status:'Completo' }]
  const openCases = () => window.dispatchEvent(new CustomEvent('opakus:navigate', { detail: { view: 'kyc-cases' } }))
  return <div className="view-enter"><SectionHeader eyebrow="CLIENTE & KYC · KYE · KYP" title="Gestão de KYC, KYE e KYP" subtitle="Visão operacional de clientes, colaboradores e parceiros através de diligência baseada em risco." action="Novo caso" /><div className="view-body"><AnalyticsStrip items={[{label:'Casos ativos',value:'1.284',delta:'+8,4% este mês',tone:'blue'},{label:'Taxa de aprovação',value:'91,8%',delta:'+2,1% vs. anterior',tone:'green'},{label:'Revisões vencidas',value:'42',delta:'12 críticas',tone:'red'},{label:'SLA médio',value:'18h 42m',delta:'−4h 12m',tone:'purple'}]} /><div className="dashboard-grid grid-2col"><DetailChart title="Volume de casos KYC" subtitle="Entradas, aprovados e encerrados" tone="purple" /><div className="card"><div className="card-header"><div><h3 className="card-title">Fila por prioridade</h3><p className="card-subtitle">Distribuição atual de casos</p></div></div><div className="card-content queue-list"><InsightRow label="Alta prioridade" value="87" detail="Requer ação hoje" tone="red"/><InsightRow label="Revisão standard" value="416" detail="Dentro do SLA" tone="blue"/><InsightRow label="Baixa prioridade" value="781" detail="Monitorização" tone="green"/><div className="stacked-bar"><i style={{width:'9%'}}/><i style={{width:'32%'}}/><i style={{width:'59%'}}/></div></div></div></div><div className="card"><div className="card-header"><div><h3 className="card-title">Casos recentes</h3><p className="card-subtitle">Últimas atualizações do workflow</p></div><button className="btn btn-secondary" onClick={openCases}>Ver todos os casos</button></div><div className="table-wrapper"><table className="table"><thead><tr><th>Cliente</th><th>Segmento</th><th>Risco</th><th>Estado</th><th>Atualizado</th></tr></thead><tbody>{cases.map((item,i)=><tr key={item.name}><td><button className="case-link" onClick={() => setSelectedCase(item)}><strong>{item.name}</strong><small>{item.type}</small></button></td><td>{['Corporate','Compliance','Fornecedor crítico','Institucional'][i]}</td><td><span className={`risk-pill ${item.risk==='Alto'?'high':item.risk==='Médio'?'medium':'low'}`}>{item.risk}</span></td><td><span className={`status ${item.status==='Documentação pendente'?'warning':'success'}`}>{item.status}</span></td><td>Hoje, {9+i}:2{i}</td></tr>)}</tbody></table></div></div></div></div>
}