import { TrendingUp, ChevronRight, AlertCircle, Clock, Zap } from 'lucide-react'
import Sparkline from '@/components/primitives/Sparkline'
import MiniBars from '@/components/primitives/MiniBars'
import Donut from '@/components/primitives/Donut'
import InsightRow from '@/components/primitives/InsightRow'

export default function OverviewView() {
  const trend = [68, 72, 70, 78, 76, 83, 81, 88, 86, 91, 89, 94]
  const heat = ['good','good','watch','good','good','risk','good','good','watch','good','risk','good']
  return (
    <div className="view-enter">
      <div className="view-header executive-header">
        <div><span className="section-kicker">OPAKUS GROUP / EXECUTIVE CENTER</span><h1 className="view-title">Visão executiva</h1><p className="view-subtitle">Painel de decisão para compliance, risco e obrigações regulatórias.</p></div>
        <div className="header-period"><span>PERÍODO DE ANÁLISE</span><strong>01 Jun — 30 Jun 2026</strong><button className="btn btn-secondary">Exportar relatório</button></div>
      </div>
      <div className="view-body executive-body">
        <div className="executive-kpis"><div className="exec-kpi primary"><span>Índice global</span><strong>87.4%</strong><small><TrendingUp /> +4.2% vs. período anterior</small><Sparkline tone="blue" points="0,36 16,34 32,30 48,32 64,22 80,25 96,12 112,8" /></div><div className="exec-kpi"><span>Controlos efectivos</span><strong>754 <em>/ 812</em></strong><small className="positive-text">92.9% concluídos</small><MiniBars values={[50,62,58,72,69,80,76,91]} /></div><div className="exec-kpi"><span>Risco residual</span><strong>8.7%</strong><small className="positive-text">−12% este mês</small><Sparkline tone="green" points="0,10 16,16 32,14 48,25 64,20 80,30 96,35 112,42" /></div><div className="exec-kpi alert"><span>Excepções abertas</span><strong>14</strong><small>3 críticas · 11 em análise</small><Sparkline tone="red" points="0,34 16,30 32,32 48,18 64,26 80,16 96,20 112,8" /></div></div>
        <div className="executive-grid main-grid">
          <div className="card executive-chart-card"><div className="card-header"><div><span className="card-eyebrow">PERFORMANCE</span><h3 className="card-title">Evolução do índice de conformidade</h3><p className="card-subtitle">Score consolidado por domínio · últimos 12 meses</p></div><div className="chart-legend"><span><i className="legend-blue"/>Score global</span><span><i className="legend-green"/>Meta 90%</span></div></div><div className="card-content"><div className="hero-chart"><div className="chart-y"><span>100%</span><span>75%</span><span>50%</span><span>25%</span><span>0%</span></div><div className="chart-plot"><div className="chart-gridlines"><i/><i/><i/><i/></div><div className="column-series">{trend.map((v,i)=><div className="column-wrap" key={i}><span className="column-value">{v}%</span><b style={{height:`${v}%`}}/><small>{['Jul','Ago','Set','Out','Nov','Dez','Jan','Fev','Mar','Abr','Mai','Jun'][i]}</small></div>)}</div><svg className="trend-overlay" viewBox="0 0 600 180" preserveAspectRatio="none"><polyline points="0,76 54,70 109,74 163,60 218,63 272,48 327,52 381,36 436,42 490,27 545,32 600,15" fill="none" stroke="var(--accent)" strokeWidth="3" strokeLinecap="round"/></svg></div></div></div></div>
          <div className="card risk-card"><div className="card-header"><div><span className="card-eyebrow">RISK INTELLIGENCE</span><h3 className="card-title">Mapa de exposição</h3><p className="card-subtitle">162 requisitos monitorizados</p></div><span className="live-tag"><i/> Ao vivo</span></div><div className="card-content"><div className="risk-donut-row"><Donut value={74} label="controlado" tone="green"/><div><strong className="risk-score">Baixa exposição</strong><p>74% dos requisitos estão dentro do apetite de risco.</p><span className="risk-trend"><TrendingUp/> 6.8 pts de melhoria</span></div></div><div className="risk-bars"><InsightRow label="Baixo risco" value="120" detail="74%" tone="green"/><InsightRow label="Risco médio" value="29" detail="18%" tone="amber"/><InsightRow label="Alto risco" value="13" detail="8%" tone="red"/></div></div></div>
        </div>
        <div className="executive-grid lower-grid"><div className="card"><div className="card-header"><div><span className="card-eyebrow">CONTROL ENVIRONMENT</span><h3 className="card-title">Saúde dos controlos</h3><p className="card-subtitle">Distribuição por estado e criticidade</p></div><button className="btn btn-ghost">Ver detalhes <ChevronRight/></button></div><div className="card-content control-health"><div className="health-ring"><Donut value={93} label="efectivos" tone="blue"/></div><div className="health-list"><InsightRow label="Controlos efectivos" value="754" detail="92.9% do total" tone="green"/><InsightRow label="Em validação" value="34" detail="4.2% do total" tone="amber"/><InsightRow label="Com excepção" value="24" detail="3.0% do total" tone="red"/></div></div></div><div className="card"><div className="card-header"><div><span className="card-eyebrow">DOMAIN COVERAGE</span><h3 className="card-title">Cobertura por domínio</h3><p className="card-subtitle">Maturidade de compliance</p></div></div><div className="card-content domain-bars"><div><span>AML / CFT <b>94%</b></span><i><em style={{width:'94%'}}/></i></div><div><span>Governação <b>88%</b></span><i><em style={{width:'88%'}}/></i></div><div><span>Reporte prudencial <b>82%</b></span><i><em style={{width:'82%'}}/></i></div><div><span>KYC e cliente <b>79%</b></span><i><em style={{width:'79%'}}/></i></div></div></div><div className="card"><div className="card-header"><div><span className="card-eyebrow">30-DAY OUTLOOK</span><h3 className="card-title">Radar executivo</h3><p className="card-subtitle">Sinais que requerem atenção</p></div></div><div className="card-content signal-list"><div><span className="signal-icon red"><AlertCircle/></span><p><strong>3 obrigações críticas</strong><small>Prazo nos próximos 7 dias</small></p><ChevronRight/></div><div><span className="signal-icon amber"><Clock/></span><p><strong>12 revisões pendentes</strong><small>Impacto operacional moderado</small></p><ChevronRight/></div><div><span className="signal-icon blue"><Zap/></span><p><strong>8 normativos novos</strong><small>Detectados pelo monitor BNA</small></p><ChevronRight/></div></div></div></div>
        <div className="card executive-foot"><div><span className="card-eyebrow">ACTIVITY MAP · REAL TIME</span><h3 className="card-title">Atividade de compliance por dia</h3></div><div className="activity-heat">{heat.concat(heat, heat).map((tone,i)=><span key={i} className={tone} title={`${i+1} eventos`}/>)}</div><div className="activity-caption"><span>Menos actividade</span><i className="good"/><i className="watch"/><i className="risk"/><span>Mais actividade</span><b>Última sincronização: há 2 min</b></div></div>
      </div>
    </div>
  )
}