'use client'

import { useState } from 'react'
import { Search, ChevronRight } from 'lucide-react'
import SectionHeader from '@/components/primitives/SectionHeader'

export default function RegulatorySearchView() {
  const [query, setQuery] = useState('')
  const [regulator, setRegulator] = useState('Todos os reguladores')
  const results = [{ code: 'Aviso 02/2026', title: 'Governação corporativa', regulator: 'BNA', date: '15 Jun 2026', impact: 'Alto' }, { code: 'Instrutivo UIF 04/2026', title: 'Prevenção de branqueamento de capitais', regulator: 'UIF', date: '10 Jun 2026', impact: 'Crítico' }, { code: 'Circular 01/2026', title: 'Reporte prudencial e liquidez', regulator: 'BNA', date: '02 Jun 2026', impact: 'Médio' }]
  const filtered = results.filter((item) => (regulator === 'Todos os reguladores' || item.regulator === regulator) && `${item.code} ${item.title}`.toLowerCase().includes(query.toLowerCase()))
  return <div className="view-enter"><SectionHeader eyebrow="NORMATIVO · INTELLIGENCE SEARCH" title="Pesquisar normativos" subtitle="Encontre requisitos por regulador, tema, impacto e estado de vigência." action="Guardar pesquisa"/><div className="view-body"><div className="search-hero"><div className="regulator-tabs">{['Todos os reguladores','BNA','UIF','Outro regulador'].map((item) => <button key={item} className={`regulator-tab ${regulator === item ? 'active' : ''}`} onClick={() => setRegulator(item)}>{item}<span>{item === 'BNA' ? '162' : item === 'UIF' ? '88' : item === 'Outro regulador' ? '142' : '392'}</span></button>)}</div><div className="regulatory-search-row"><div className="regulatory-search-field"><Search size={17}/><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Código, palavra-chave, obrigação ou tema"/></div><button className="btn btn-secondary" onClick={() => setQuery('')}>Limpar</button><button className="btn btn-primary">Pesquisar</button></div><div className="search-suggestions"><span>Pesquisas recentes</span><button onClick={() => setQuery('AML')}>AML / CFT</button><button onClick={() => setQuery('reporte prudencial')}>Reporte prudencial</button><button onClick={() => setQuery('governação')}>Governação</button></div></div><div className="search-results-header"><div><span className="section-kicker">RESULTADOS INDEXADOS</span><h2>{filtered.length} normativos encontrados</h2><p>Ordenados por relevância · sincronizados há 2 min</p></div><button className="btn btn-secondary">Filtros avançados</button></div><div className="card search-results-card"><div className="table-wrapper"><table className="table"><thead><tr><th>Normativo</th><th>Regulador</th><th>Publicação</th><th>Impacto</th><th>Estado</th><th/></tr></thead><tbody>{filtered.map((item) => <tr key={item.code}><td><strong>{item.code}</strong><small className="result-title">{item.title}</small></td><td><span className="regulator-badge">{item.regulator}</span></td><td>{item.date}</td><td><span className={`risk-pill ${item.impact === 'Crítico' ? 'high' : item.impact === 'Alto' ? 'medium' : 'low'}`}>{item.impact}</span></td><td><span className="status success">Em vigor</span></td><td><button className="icon-btn" aria-label={`Abrir ${item.code}`}><ChevronRight size={16}/></button></td></tr>)}</tbody></table></div></div></div></div>
}