'use client'

import { ChevronRight } from 'lucide-react'
import SectionHeader from '@/components/primitives/SectionHeader'
import AnalyticsStrip from '@/components/primitives/AnalyticsStrip'
import DetailChart from '@/components/primitives/DetailChart'
import InsightRow from '@/components/primitives/InsightRow'

export default function UsersView() {
  const openProfile = (name: string) => window.dispatchEvent(new CustomEvent('opakus:navigate', { detail: { view: 'user-profile', name } }))
  return <div className="view-enter"><SectionHeader eyebrow="GESTÃO DA PLATAFORMA · IAM" title="Utilizadores e roles" subtitle="Administre acessos, funções e segregação de responsabilidades da plataforma." action="Convidar utilizador"/><div className="view-body"><AnalyticsStrip items={[{label:'Utilizadores activos',value:'48',delta:'+3 este mês',tone:'blue'},{label:'Convites pendentes',value:'05',delta:'2 expiram amanhã',tone:'amber'},{label:'Roles configuradas',value:'09',delta:'3 customizadas',tone:'purple'},{label:'Acessos revistos',value:'96%',delta:'+4,1% este trimestre',tone:'green'}]}/><div className="dashboard-grid grid-2col"><DetailChart title="Actividade de utilizadores" subtitle="Sessões e acessos · últimos 30 dias" tone="purple"/><div className="card"><div className="card-header"><div><span className="card-eyebrow">ACCESS CONTROL</span><h3 className="card-title">Distribuição por role</h3><p className="card-subtitle">Princípio do menor privilégio</p></div></div><div className="card-content"><InsightRow label="Compliance Officer" value="12" detail="Acesso operacional" tone="blue"/><InsightRow label="Risk Manager" value="8" detail="Acesso a risco" tone="purple"/><InsightRow label="Auditor" value="6" detail="Somente leitura" tone="amber"/><InsightRow label="Administrador" value="3" detail="Acesso privilegiado" tone="red"/></div></div></div><div className="card user-table"><div className="card-header"><div><h3 className="card-title">Utilizadores da organização</h3><p className="card-subtitle">Última revisão de acessos: 18 Jun 2026</p></div><button className="btn btn-secondary">Rever acessos</button></div><div className="table-wrapper"><table className="table"><thead><tr><th>Utilizador</th><th>Departamento</th><th>Role</th><th>Último acesso</th><th>Estado</th><th/></tr></thead><tbody>{[['Marta Domingos','Compliance','Compliance Officer'],['João Manuel','Risco','Risk Manager'],['Ana Costa','Auditoria','Auditor'],['Paulo Silva','IT & Segurança','Administrador']].map(([name,dept,role],i)=><tr key={name}><td><div className="user-cell"><span className="avatar-small">{name.split(' ').map((n) => n[0]).join('')}</span><strong>{name}</strong></div></td><td>{dept}</td><td><span className="role-badge">{role}</span></td><td>{i + 1} h atrás</td><td><span className="status success">Activo</span></td><td><button className="btn btn-ghost" onClick={() => openProfile(name)}>Ver perfil <ChevronRight size={14}/></button></td></tr>)}</tbody></table></div></div></div></div>
}